name: Deploy Laravel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Show server environment
        run: |
          php -v
          composer --version
          git --version

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Cache Laravel configuration
        run: |
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Optimize Laravel
        run: php artisan optimize

      - name: Health check
        run: php artisan about